### ISSUE TITLE
Is it possible to store the password directly from the config file?

### ISSUE THREAD

**Issue by hendrawd** [chrmarti/vscode-ssh#1]
Like this one
```
Host myServer
    HostName myServerIpAddress
    Port 22222
    User webadmin
    Password xxxxx
```

**Comment by chrmarti** [comment]
This is a limitation of the ssh config from the openssh package and not under the VSCode extension's control. See e.g.: https://stackoverflow.com/questions/39347365/specifying-password-in-ssh-config-file
